"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";

type Section = "任务总览" | "企业审核" | "财务退款" | "客服工单" | "风险告警";
type Admin = { id: string; email: string; displayName: string; role: "super_admin" | "operator" | "finance" | "support" | "risk" };
type Data = { currentAdmin: Admin; permissions: { tenants: boolean; refunds: boolean; tickets: boolean; risk: boolean }; summary: { tenantTasks: number; refundTasks: number; ticketTasks: number; riskTasks: number }; tenants: Array<Record<string, unknown>>; refunds: Array<Record<string, unknown>>; tickets: Array<Record<string, unknown>>; alerts: Array<Record<string, unknown>> };

const allNav: Array<[Section, string, keyof Data["permissions"] | null]> = [["任务总览", "01", null], ["企业审核", "02", "tenants"], ["财务退款", "03", "refunds"], ["客服工单", "04", "tickets"], ["风险告警", "05", "risk"]];
const roleNames = { super_admin: "超级管理员", operator: "运营管理员", finance: "财务管理员", support: "客服主管", risk: "风控管理员" };
function date(value: unknown) { return value ? new Date(String(value)).toLocaleString("zh-CN") : "—"; }
function money(value: unknown) { return `¥${(Number(value || 0) / 100).toFixed(2)}`; }
async function api<T>(url: string, init?: RequestInit) { const response = await fetch(url, init); const data = await response.json() as T & { error?: string }; if (!response.ok) throw new Error(data.error || "请求失败"); return data; }

export default function AdminDashboard({ user, admin }: { user: { displayName: string; email: string }; admin: Admin }) {
  const [active, setActive] = useState<Section>("任务总览"); const [data, setData] = useState<Data | null>(null); const [busy, setBusy] = useState(""); const [notice, setNotice] = useState<{ kind: "ok" | "error"; text: string } | null>(null);
  const load = useCallback(async () => setData(await api<Data>("/api/admin")), []);
  useEffect(() => { const timer = setTimeout(() => void load().catch((error) => setNotice({ kind: "error", text: error.message })), 0); return () => clearTimeout(timer); }, [load]);
  const nav = useMemo(() => allNav.filter(([, , permission]) => !permission || data?.permissions[permission]), [data]);
  async function action(body: Record<string, unknown>, message: string) { setBusy(String(body.id || body.tenantId || body.action)); try { await api("/api/admin", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); await load(); setNotice({ kind: "ok", text: message }); } catch (error) { setNotice({ kind: "error", text: error instanceof Error ? error.message : "操作失败" }); } finally { setBusy(""); } }
  const empty = (text: string) => <div className="source-empty">{text}</div>;
  const taskItems = [{ label: "企业审核", value: data?.summary.tenantTasks || 0, color: "#4d8cf2" }, { label: "财务退款", value: data?.summary.refundTasks || 0, color: "#8a66ea" }, { label: "客服工单", value: data?.summary.ticketTasks || 0, color: "#28b78c" }, { label: "风险告警", value: data?.summary.riskTasks || 0, color: "#e18363" }];
  const taskTotal = taskItems.reduce((sum, item) => sum + item.value, 0);
  function overview() { return <><section className="admin-welcome"><div><p className="section-kicker">Operations workbench</p><h2>今天该处理什么，一眼看清</h2><p>这里只处理日常运营任务；套餐、商户号、平台管理员和全局配置只在超级管理员控制台修改。</p></div><span>{roleNames[admin.role]}</span></section><section className="metric-grid"><article><span>企业待办</span><strong>{data?.summary.tenantTasks || 0}</strong><small>注册资料与状态异常</small></article><article><span>退款待办</span><strong>{data?.summary.refundTasks || 0}</strong><small>财务审核与通道处理</small></article><article><span>客服待办</span><strong>{data?.summary.ticketTasks || 0}</strong><small>开放工单与 SLA</small></article><article><span>风险告警</span><strong>{data?.summary.riskTasks || 0}</strong><small>超时与通知失败</small></article></section><section className="card admin-task-visual"><div className="card-head compact"><div><p className="section-kicker">Task distribution</p><h2>待办任务分布</h2></div><span className={taskTotal ? "warn-badge" : "live-badge"}>{taskTotal ? `${taskTotal} 项待处理` : "全部已清空"}</span></div><div className="task-distribution">{taskItems.map((item) => <div key={item.label}><span><i style={{ background:item.color }}/>{item.label}</span><b>{item.value}</b><em><i style={{ width:`${taskTotal ? Math.max(3, item.value / taskTotal * 100) : 0}%`, background:item.color }}/></em><small>{taskTotal ? Math.round(item.value / taskTotal * 100) : 0}%</small></div>)}</div></section><section className="admin-queue-grid">{nav.filter(([name]) => name !== "任务总览").map(([name, index]) => <button key={name} onClick={() => setActive(name)}><span>{String(index + 1).padStart(2, "0")}</span><div><b>{name}</b><small>进入角色授权的处理队列</small></div><em>→</em></button>)}</section></>; }
  function tenants() { return <section className="card platform-table-card"><div className="card-head"><div><p className="section-kicker">Enterprise onboarding</p><h2>企业审核与状态</h2></div><span className="count-badge">{data?.tenants.length || 0} 项</span></div>{!data?.tenants.length ? empty("没有待审核或状态异常的企业。") : <div className="admin-list">{data.tenants.map((row) => <article key={String(row.id)}><div><b>{String(row.company_name || row.name)}</b><small>{String(row.billing_email || "未填写账单邮箱")} · {date(row.created_at)} · {String(row.documents)} 份文档</small></div><i className={`state ${String(row.status)}`}>{row.onboarding_completed ? String(row.status) : "资料未完成"}</i><button className="secondary-button compact" disabled={busy === row.id} onClick={() => void action({ action: "tenant_status", tenantId: row.id, status: row.status === "active" ? "suspended" : "active" }, "企业状态已更新。")}>{row.status === "active" ? "暂停服务" : "恢复服务"}</button></article>)}</div>}</section>; }
  function refunds() { return <section className="card platform-table-card"><div className="card-head"><div><p className="section-kicker">Finance queue</p><h2>退款审核</h2></div><span className="count-badge">{data?.refunds.length || 0} 笔</span></div>{!data?.refunds.length ? empty("没有待处理退款。") : <div className="admin-list">{data.refunds.map((row) => <article key={String(row.id)}><div><b>{String(row.tenant_name)} · {money(row.amount_cents)}</b><small>{String(row.order_no)} · {String(row.provider)} · {String(row.reason)} · {date(row.created_at)}</small></div><i className={`state ${String(row.status)}`}>{String(row.status)}</i>{row.status === "requested" && <div className="compact-actions"><button className="secondary-button compact" onClick={() => void action({ action: "refund_review", id: row.id, decision: "approve" }, "退款已审核通过，等待支付通道处理。")}>通过</button><button className="ghost-danger bordered" onClick={() => void action({ action: "refund_review", id: row.id, decision: "reject" }, "退款申请已拒绝。")}>拒绝</button></div>}</article>)}</div>}</section>; }
  function tickets() { return <section className="card platform-table-card"><div className="card-head"><div><p className="section-kicker">Support queue</p><h2>客服工单与 SLA</h2></div><span className="count-badge">{data?.tickets.length || 0} 个</span></div>{!data?.tickets.length ? empty("没有开放中的客服工单。") : <div className="admin-list">{data.tickets.map((row) => <article key={String(row.id)}><div><b>{String(row.subject)}</b><small>{String(row.tenant_name)} · {String(row.contact || "未留联系方式")} · SLA {date(row.sla_due_at)}</small></div><i className={`priority ${String(row.priority)}`}>{String(row.priority)}</i><div className="compact-actions"><button className="secondary-button compact" onClick={() => void action({ action: "ticket_status", id: row.id, status: "processing" }, "工单已开始处理。")}>接单</button><button className="primary-button fit compact" onClick={() => void action({ action: "ticket_status", id: row.id, status: "resolved" }, "工单已解决。")}>解决</button></div></article>)}</div>}</section>; }
  function risks() { return <section className="card platform-table-card"><div className="card-head"><div><p className="section-kicker">Risk & delivery</p><h2>风险告警</h2></div><span className="count-badge">{data?.alerts.length || 0} 条</span></div>{!data?.alerts.length ? empty("没有通知失败或系统风险告警。") : <div className="admin-list">{data.alerts.map((row) => <article key={String(row.id)}><div><b>{String(row.event_type)} · {String(row.channel)}</b><small>租户 {String(row.tenant_id)} · 重试 {String(row.attempts)} 次 · {date(row.created_at)}</small><p>{String(row.last_error || "未知错误")}</p></div><i className="state suspended">待排查</i></article>)}</div>}</section>; }
  return <main className="app-shell admin-shell"><aside className="sidebar admin-sidebar"><div className="brand"><span className="brand-mark">K</span><span><b>KnowFlow</b><small>内部管理台</small></span></div><nav><div className="nav-group"><label>运营任务</label>{nav.map(([label, index]) => <button key={label} className={active === label ? "nav-item active" : "nav-item"} onClick={() => setActive(label)}><span className="nav-index">{index}</span>{label}</button>)}</div></nav>{admin.role === "super_admin" && <Link className="console-switch" href="/platform"><span>↗</span><div><b>超级管理员控制台</b><small>经营与全局配置</small></div></Link>}<div className="sidebar-foot"><span className="status-dot"/>{roleNames[admin.role]}</div></aside><section className="workspace"><header className="topbar"><div><p className="eyebrow">KnowFlow PLATFORM OPERATIONS</p><h1>{active}</h1></div><div className="user-menu"><span className="avatar">{user.displayName.slice(0, 1)}</span><div><b>{user.displayName}</b><small>{roleNames[admin.role]}</small></div><a href="/account">账号</a><a href="/logout">退出</a></div></header>{notice && <div className={`toast ${notice.kind}`}><span>{notice.kind === "ok" ? "✓" : "!"}</span>{notice.text}<button onClick={() => setNotice(null)}>×</button></div>}<div className="page-content">{!data ? empty("正在加载运营任务…") : active === "任务总览" ? overview() : active === "企业审核" ? tenants() : active === "财务退款" ? refunds() : active === "客服工单" ? tickets() : risks()}</div></section></main>;
}
