"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import CustomerServiceConsole from "./customer-service-console";

type AssistantConfig = { id: string; publicId: string; publicEnabled: boolean; brandName: string; welcomeMessage: string; themeColor: string; leadCaptureEnabled: boolean; handoffEnabled: boolean; handoffLabel: string; industryTemplate: string; suggestedQuestions: string[]; allowedDomains: string[]; privacyNotice: string; privacyPolicyUrl: string; privacyVersion: string; retentionDays: number; version: number };
type Lead = { id: string; name: string; company: string; contact: string; need: string; status: string; assigneeMemberId: string | null; estimatedValueCents: number; notes: string; createdAt: string };
type Ticket = { id: string; subject: string; description: string; contact: string; priority: string; status: string; assigneeMemberId: string | null; slaDueAt: string | null; firstResponseAt: string | null; resolvedAt: string | null; createdAt: string };
type Member = { id: string; email: string; displayName: string; role: string; status: string };
type CommercialData = {
  assistant: AssistantConfig; templates: Array<{ code: string; name: string }>;
  summary: { conversations: number; resolved: number; grounded: number; unresolved: number; resolutionRate: number; leads: number; openTickets: number; pipelineCents: number; wonCents: number; revenueCents: number; costCents: number; grossProfitCents: number };
  plan: { code: string; name: string; widgetConversationQuota: number; leadQuota: number; features: string[] };
  monthly: { month: string; conversations: number; leads: number }; leads: Lead[]; tickets: Ticket[];
  unresolved: Array<{ id: string; firstQuestion: string; lastQuestion: string; messageCount: number; startedAt: string; lastMessageAt: string }>;
};

async function request<T>(url: string, init?: RequestInit) {
  const headers = new Headers(init?.headers); const tenantId = localStorage.getItem("knowflow_tenant_id"); if (tenantId) headers.set("x-tenant-id", tenantId);
  const response = await fetch(url, { ...init, headers }); const data = await response.json() as T & { error?: string };
  if (!response.ok) throw new Error(data.error || `请求失败（${response.status}）`); return data;
}
function money(cents: number) { return new Intl.NumberFormat("zh-CN", { style: "currency", currency: "CNY", maximumFractionDigits: 0 }).format(cents / 100); }
function date(value: string) { return new Date(value).toLocaleString("zh-CN", { month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" }); }
const leadStatus: Record<string, string> = { new: "新线索", contacted: "已联系", qualified: "高意向", won: "已成交", lost: "已流失" };
const ticketStatus: Record<string, string> = { open: "待处理", processing: "处理中", resolved: "已解决", closed: "已关闭" };

export default function CommercialPanel({ canAdmin, members, onNotice }: { canAdmin: boolean; members: Member[]; onNotice: (notice: { kind: "ok" | "error"; text: string }) => void }) {
  const [data, setData] = useState<CommercialData | null>(null); const [config, setConfig] = useState<AssistantConfig | null>(null);
  const [busy, setBusy] = useState<string | null>(null); const [template, setTemplate] = useState("manufacturing_after_sales");
  const load = useCallback(async () => { const next = await request<CommercialData>("/api/commercial"); setData(next); setConfig(next.assistant); setTemplate(next.assistant.industryTemplate); }, []);
  useEffect(() => { const timer = window.setTimeout(() => { void load().catch((error) => onNotice({ kind: "error", text: error instanceof Error ? error.message : "商业数据加载失败" })); }, 0); return () => window.clearTimeout(timer); }, [load, onNotice]);
  const origin = typeof window === "undefined" ? "https://your-site.example" : window.location.origin;
  const publicUrl = config?.publicId ? `${origin}/chat/${config.publicId}` : "";
  const embed = useMemo(() => `<script src="${origin}/widget.js?publicId=${config?.publicId || ""}" async></script>`, [origin, config?.publicId]);

  async function copy(value: string) { await navigator.clipboard.writeText(value); onNotice({ kind: "ok", text: "嵌入代码已复制，可粘贴到企业官网。" }); }
  async function saveConfig(event: FormEvent) {
    event.preventDefault(); if (!config) return; setBusy("config");
    try { const result = await request<{ message: string }>("/api/commercial", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "saveWidget", ...config }) }); await load(); onNotice({ kind: "ok", text: result.message }); }
    catch (error) { onNotice({ kind: "error", text: error instanceof Error ? error.message : "发布失败" }); } finally { setBusy(null); }
  }
  async function applyTemplate() {
    if (!confirm("应用行业模板会同步更新助手系统提示词、欢迎语和推荐问题。继续？")) return; setBusy("template");
    try { const result = await request<{ message: string }>("/api/commercial", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "applyTemplate", template }) }); await load(); onNotice({ kind: "ok", text: result.message }); }
    catch (error) { onNotice({ kind: "error", text: error instanceof Error ? error.message : "模板应用失败" }); } finally { setBusy(null); }
  }
  async function publishNow() { setBusy("publish"); try { const result = await request<{ message: string }>("/api/commercial", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "publishNow" }) }); await load(); onNotice({ kind: "ok", text: result.message }); } catch (error) { onNotice({ kind: "error", text: error instanceof Error ? error.message : "发布失败" }); } finally { setBusy(null); } }
  async function updateLead(item: Lead, status = item.status, valueYuan = item.estimatedValueCents / 100, assigneeMemberId = item.assigneeMemberId) {
    setBusy(item.id); try { await request("/api/commercial", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ entity: "lead", id: item.id, status, assigneeMemberId, estimatedValueYuan: valueYuan, notes: item.notes }) }); await load(); onNotice({ kind: "ok", text: "销售线索已更新。" }); }
    catch (error) { onNotice({ kind: "error", text: error instanceof Error ? error.message : "更新失败" }); } finally { setBusy(null); }
  }
  async function setLeadValue(item: Lead) { const value = prompt("预计成交金额（元）", String(item.estimatedValueCents / 100)); if (value === null || !Number.isFinite(Number(value)) || Number(value) < 0) return; await updateLead(item, item.status, Number(value)); }
  async function updateTicket(item: Ticket, status = item.status, assigneeMemberId = item.assigneeMemberId, priority = item.priority) {
    setBusy(item.id); try { await request("/api/commercial", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ entity: "ticket", id: item.id, status, assigneeMemberId, priority }) }); await load(); onNotice({ kind: "ok", text: "工单、负责人和 SLA 记录已更新。" }); }
    catch (error) { onNotice({ kind: "error", text: error instanceof Error ? error.message : "更新失败" }); } finally { setBusy(null); }
  }

  if (!data || !config) return <section className="card commercial-loading"><span className="spinner dark"/> 正在加载客户转化数据…</section>;
  const leadAvailable = data.plan.features.includes("lead_capture"); const handoffAvailable = data.plan.features.includes("handoff");
  return <>
    <section className="commercial-hero card"><div><p className="section-kicker">Revenue operations</p><h2>把企业资料变成能获客、能转人工、能计算产出的 AI 员工</h2><p>访客提问 → RAG 回答 → 未解决问题沉淀 → 留资 / 工单 → 销售跟进 → 成交金额。</p></div><div className="commercial-plan"><span>{data.plan.name}</span><b>{data.monthly.conversations}/{data.plan.widgetConversationQuota}</b><small>本月客服会话</small>{!config.publicEnabled && <button className="primary-button fit" onClick={() => void publishNow()} disabled={!canAdmin || busy === "publish"}>一键发布客服</button>}</div></section>
    <section className="metric-grid commercial-metrics"><article><span>近 30 天会话</span><strong>{data.summary.conversations}</strong><small>官网智能客服访客</small></article><article><span>人工确认解决率</span><strong className={data.summary.resolutionRate >= 70 ? "good" : "warn"}>{data.summary.conversations ? `${data.summary.resolutionRate}%` : "—"}</strong><small>{data.summary.resolved} 用户确认 · {data.summary.grounded} 有依据回答</small></article><article><span>销售线索</span><strong>{data.summary.leads}</strong><small>{data.monthly.leads}/{data.plan.leadQuota} 本月额度</small></article><article><span>预计商机</span><strong>{money(data.summary.pipelineCents)}</strong><small>已成交 {money(data.summary.wonCents)}</small></article></section>
    <section className="commercial-finance"><span>订阅实收 <b>{money(data.summary.revenueCents)}</b></span><span>模型/OCR 成本 <b>{money(data.summary.costCents)}</b></span><span>毛利润 <b>{money(data.summary.grossProfitCents)}</b></span></section>
    <CustomerServiceConsole canAdmin={canAdmin} onNotice={onNotice}/>
    {(!leadAvailable || !handoffAvailable) && <section className="commercial-upgrade"><b>当前为{data.plan.name}</b><span>网页问答已可使用；成长版解锁销售留资、转人工工单和完整转化闭环。</span></section>}
    <div className="commercial-layout">
      <section className="card form-card"><div className="card-head"><div><p className="section-kicker">Website widget</p><h2>官网客服发布设置</h2></div><span className={config.publicEnabled ? "live-badge" : "warn-badge"}>{config.publicEnabled ? "已上线" : "未公开"}</span></div>
        <div className="template-row"><select value={template} onChange={(event) => setTemplate(event.target.value)}>{data.templates.map((item) => <option value={item.code} key={item.code}>{item.name}</option>)}</select><button className="secondary-button" type="button" onClick={applyTemplate} disabled={!canAdmin || busy === "template"}>应用行业模板</button></div>
        <form className="settings-form" onSubmit={saveConfig}><label className="reuse-secret"><input type="checkbox" checked={config.publicEnabled} onChange={(event) => setConfig({ ...config, publicEnabled: event.target.checked })}/><span><b>公开官网智能客服</b><small>关闭后公开链接立即停止服务，历史会话和线索不会删除。</small></span></label><div className="field-grid"><div><label>品牌 / 助手名称</label><input value={config.brandName} onChange={(event) => setConfig({ ...config, brandName: event.target.value })}/></div><div><label>主题颜色</label><input type="color" value={config.themeColor} onChange={(event) => setConfig({ ...config, themeColor: event.target.value })}/></div></div><label>欢迎语</label><textarea rows={3} value={config.welcomeMessage} onChange={(event) => setConfig({ ...config, welcomeMessage: event.target.value })}/><label>推荐问题<span>每行一个，最多 6 个</span></label><textarea rows={4} value={config.suggestedQuestions.join("\n")} onChange={(event) => setConfig({ ...config, suggestedQuestions: event.target.value.split("\n").slice(0, 6) })}/><div className="field-grid"><label className="reuse-secret"><input type="checkbox" checked={config.leadCaptureEnabled} onChange={(event) => setConfig({ ...config, leadCaptureEnabled: event.target.checked })}/><span><b>销售线索收集</b><small>{leadAvailable ? "收集公司、联系方式和采购需求" : "成长版功能"}</small></span></label><label className="reuse-secret"><input type="checkbox" checked={config.handoffEnabled} onChange={(event) => setConfig({ ...config, handoffEnabled: event.target.checked })}/><span><b>转人工工单</b><small>{handoffAvailable ? "AI 无法回答时承接客户" : "成长版功能"}</small></span></label></div><label>人工按钮名称</label><input value={config.handoffLabel} onChange={(event) => setConfig({ ...config, handoffLabel: event.target.value })}/><label>官网域名白名单<span>每行一个，例如 example.com 或 *.example.com；留空允许所有域名</span></label><textarea rows={3} value={config.allowedDomains.join("\n")} onChange={(event) => setConfig({ ...config, allowedDomains: event.target.value.split("\n").slice(0, 20) })}/><label>隐私告知</label><textarea rows={3} value={config.privacyNotice} onChange={(event) => setConfig({ ...config, privacyNotice: event.target.value })}/><div className="field-grid"><div><label>隐私政策 HTTPS 地址</label><input value={config.privacyPolicyUrl} onChange={(event) => setConfig({ ...config, privacyPolicyUrl: event.target.value })}/></div><div><label>客户数据保存天数</label><input type="number" min="30" max="1095" value={config.retentionDays} onChange={(event) => setConfig({ ...config, retentionDays: Number(event.target.value) })}/></div></div><button className="primary-button" disabled={!canAdmin || busy === "config"}>{busy === "config" ? "发布中…" : "保存并发布"}</button></form>
      </section>
      <aside className="card widget-publish"><div><p className="section-kicker">Floating widget</p><h2>右下角悬浮客服</h2></div><div className="widget-preview-mini" style={{ borderColor: config.themeColor }}><span style={{ background: config.themeColor }}>K</span><div><b>{config.brandName}</b><small>{config.publicEnabled ? "在线接待客户" : "等待发布"}</small></div></div><label>公开测试链接</label><code>{publicUrl}</code><div className="form-actions"><button className="secondary-button" onClick={() => copy(publicUrl)}>复制链接</button><a className={`primary-button fit ${!config.publicEnabled ? "disabled" : ""}`} href={config.publicEnabled ? publicUrl : undefined} target="_blank" rel="noreferrer">打开测试</a></div><label>官网悬浮组件代码</label><pre>{embed}</pre><button className="secondary-button full" onClick={() => copy(embed)}>复制组件代码</button><p>脚本自动生成右下角按钮、开关动画和隔离 iframe；域名白名单开启后，非授权网站无法取得签名嵌入 Token。</p></aside>
    </div>
    <section className="card commercial-table-card"><div className="card-head"><div><p className="section-kicker">Sales pipeline</p><h2>销售线索漏斗</h2></div><span className="count-badge">{data.leads.length} 条</span></div>{data.leads.length === 0 ? <div className="commercial-empty">客户在公开客服点击“获取方案”并同意隐私告知后，会出现在这里。</div> : <div className="commercial-table"><div className="commercial-row commercial-head"><span>客户 / 联系方式</span><span>需求 / 负责人</span><span>预计金额</span><span>状态</span><span>时间</span></div>{data.leads.map((item) => <div className="commercial-row" key={item.id}><span><b>{item.name || "未填写称呼"}{item.company ? ` · ${item.company}` : ""}</b><small>{item.contact}</small></span><span title={item.need}><small>{item.need || "未填写具体需求"}</small><select value={item.assigneeMemberId || ""} onChange={(event) => void updateLead(item, item.status, item.estimatedValueCents / 100, event.target.value || null)} disabled={!canAdmin || busy === item.id}><option value="">未分配</option>{members.filter((member) => member.status === "active").map((member) => <option value={member.id} key={member.id}>{member.displayName || member.email}</option>)}</select></span><span><button className="value-button" onClick={() => void setLeadValue(item)} disabled={!canAdmin || busy === item.id}>{money(item.estimatedValueCents)} ✎</button></span><span><select value={item.status} onChange={(event) => void updateLead(item, event.target.value)} disabled={!canAdmin || busy === item.id}>{Object.entries(leadStatus).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></span><span>{date(item.createdAt)}</span></div>)}</div>}</section>
    <div className="commercial-bottom">
      <section className="card commercial-list"><div className="card-head"><div><p className="section-kicker">Human handoff</p><h2>人工工单与 SLA</h2></div><span className="count-badge">{data.summary.openTickets} 待处理</span></div>{data.tickets.length === 0 ? <div className="commercial-empty compact">暂无人工工单。</div> : data.tickets.map((item) => { const overdue = item.slaDueAt && new Date(item.slaDueAt) < new Date() && !["resolved", "closed"].includes(item.status); return <article key={item.id} className={overdue ? "sla-overdue" : ""}><div><b>{item.subject}</b><p>{item.description}</p><small>{item.contact || "未留联系方式"} · 创建 {date(item.createdAt)} · SLA {item.slaDueAt ? date(item.slaDueAt) : "—"}{overdue ? " · 已超时" : ""}</small></div><div className="ticket-controls"><select value={item.assigneeMemberId || ""} onChange={(event) => void updateTicket(item, item.status, event.target.value || null)} disabled={!canAdmin || busy === item.id}><option value="">未分配</option>{members.filter((member) => member.status === "active").map((member) => <option value={member.id} key={member.id}>{member.displayName || member.email}</option>)}</select><select value={item.priority} onChange={(event) => void updateTicket(item, item.status, item.assigneeMemberId, event.target.value)} disabled={!canAdmin || busy === item.id}><option value="low">低</option><option value="normal">普通</option><option value="high">高</option><option value="urgent">紧急</option></select><select value={item.status} onChange={(event) => void updateTicket(item, event.target.value)} disabled={!canAdmin || busy === item.id}>{Object.entries(ticketStatus).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></div></article>; })}</section>
      <section className="card commercial-list"><div className="card-head"><div><p className="section-kicker">Knowledge gaps</p><h2>未解决问题</h2></div><span className="count-badge">{data.unresolved.length} 条</span></div>{data.unresolved.length === 0 ? <div className="commercial-empty compact">暂无未解决问题；上线后这里会形成知识库补充清单。</div> : data.unresolved.map((item) => <article key={item.id}><div><b>{item.lastQuestion}</b><p>首次：{item.firstQuestion}</p><small>{item.messageCount} 条消息 · {date(item.lastMessageAt)}</small></div><span className="gap-tag">待补知识</span></article>)}</section>
    </div>
  </>;
}
