"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import CommercialPanel from "./commercial-panel";
import CustomerServiceConsole from "./customer-service-console";

type Member = { id: string; email: string; displayName: string; role: string; status: string };
type Notice = { kind: "ok" | "error"; text: string };
type Stage = { name: string; status: string; detail: string };
type Trace = { id: string; requestId: string; model: string; question: string; answer: string; totalTokens: number; latencyMs: number; costMicros: number; grounded: boolean; qualityScore: number; status: string; createdAt: string; sources: Array<Record<string, unknown>>; stages: Stage[] };
type Visitor = { id: string; mode: string; status: string; firstQuestion: string; lastQuestion: string; visitorMaskedIp: string; visitorCountry: string; visitorRegion: string; visitorCity: string; visitorReferer: string; visitorEmail: string; lastVisitorSeenAt: string | null; offlineEmailSentAt: string | null; lastMessageAt: string };
type DashboardData = { summary: { conversations: number; aiResolved: number; automationRate: number; handoff: number; handoffRate: number; resolved: number; faqCount: number; faqHits: number; modelCallsSaved: number; leads: number; pipelineCents: number; wonCents: number; openTickets: number; modelRequests: number; modelCostCents: number; avgLatencyMs: number; costPerConversationCents: number }; daily: Array<{ day: string; conversations: number; aiResolved: number; handoff: number }>; countries: Array<{ country: string; count: number }>; traces: Trace[]; visitors: Visitor[] };
type Tab = "总览" | "实时会话" | "FAQ" | "数据报表" | "Trace 日志" | "访客与跟进" | "网站 Widget";
const tabs: Array<{ key: Tab; icon: string; desc: string }> = [
  { key: "总览", icon: "⌂", desc: "AI 客服价值" }, { key: "实时会话", icon: "◉", desc: "人工接待" }, { key: "FAQ", icon: "⚡", desc: "固定问题直答" },
  { key: "数据报表", icon: "▥", desc: "解决率与成本" }, { key: "Trace 日志", icon: "⌁", desc: "RAG / 模型诊断" }, { key: "访客与跟进", icon: "◎", desc: "来源与离线邮箱" },
  { key: "网站 Widget", icon: "✦", desc: "官网悬浮客服" },
];
async function api<T>(url: string) { const headers = new Headers(); const tenantId = localStorage.getItem("knowflow_tenant_id"); if (tenantId) headers.set("x-tenant-id", tenantId); const response = await fetch(url, { headers }); const data = await response.json() as T & { error?: string }; if (!response.ok) throw new Error(data.error || "客服中心加载失败"); return data; }
function money(cents: number) { return new Intl.NumberFormat("zh-CN", { style: "currency", currency: "CNY", maximumFractionDigits: 0 }).format(cents / 100); }
function time(value?: string | null) { return value ? new Date(value).toLocaleString("zh-CN", { month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" }) : "—"; }
function host(value: string) { try { return new URL(value).hostname; } catch { return value || "直接访问"; } }
function online(value: string | null) { return Boolean(value && Date.now() - Date.parse(value) < 90_000); }

export default function CustomerServiceCenter({ canAdmin, members, onNotice }: { canAdmin: boolean; members: Member[]; onNotice: (notice: Notice) => void }) {
  const [tab, setTab] = useState<Tab>("总览"); const [data, setData] = useState<DashboardData | null>(null); const [selectedTrace, setSelectedTrace] = useState<string>("");
  const load = useCallback(async () => { const next = await api<DashboardData>("/api/commercial/service-dashboard"); setData(next); setSelectedTrace((current) => current && next.traces.some((item) => item.id === current) ? current : (next.traces[0]?.id || "")); }, []);
  useEffect(() => { const initial = window.setTimeout(() => { void load().catch((error) => onNotice({ kind: "error", text: error instanceof Error ? error.message : "客服中心加载失败" })); }, 0); const timer = window.setInterval(() => void load(), 15000); return () => { window.clearTimeout(initial); window.clearInterval(timer); }; }, [load, onNotice]);
  const trace = useMemo(() => data?.traces.find((item) => item.id === selectedTrace) || null, [data, selectedTrace]);
  const maxDaily = Math.max(1, ...(data?.daily.map((item) => item.conversations) || [1]));
  return <div style={{ display: "grid", gap: 16 }}>
    <section className="commercial-hero card"><div><p className="section-kicker">Customer service center</p><h2>客服中心</h2><p>以后所有 AI 客服能力都从这里进入：接待访客、FAQ、价值报表、Trace 诊断、访客来源、离线跟进和官网 Widget。</p></div><div className="commercial-plan"><span>固定入口</span><b>工作台 → 客服中心</b><small>不再把客服功能散落到其他页面</small></div></section>
    <nav className="card" style={{ padding: 12, display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(128px,1fr))", gap: 8 }}>{tabs.map((item) => <button key={item.key} onClick={() => setTab(item.key)} className={tab === item.key ? "primary-button" : "secondary-button"} style={{ minHeight: 66, display: "grid", gap: 2, alignContent: "center", textAlign: "left" }}><span style={{ fontSize: 17 }}>{item.icon} {item.key}</span><small style={{ opacity: .72 }}>{item.desc}</small></button>)}</nav>
    {!data ? <section className="card commercial-loading"><span className="spinner dark"/> 正在加载客服中心…</section> : null}
    {data && tab === "总览" && <>
      <section className="metric-grid commercial-metrics"><article><span>AI 自动解决率</span><strong className={data.summary.automationRate >= 60 ? "good" : "warn"}>{data.summary.automationRate}%</strong><small>{data.summary.aiResolved}/{data.summary.conversations} 个会话由 AI 解决</small></article><article><span>FAQ 节省模型调用</span><strong>{data.summary.modelCallsSaved}</strong><small>{data.summary.faqCount} 条 FAQ · 命中即不调用 LLM</small></article><article><span>人工转接率</span><strong>{data.summary.handoffRate}%</strong><small>{data.summary.handoff} 个会话进入人工</small></article><article><span>近 30 天模型成本</span><strong>{money(data.summary.modelCostCents)}</strong><small>单会话约 {money(data.summary.costPerConversationCents)}</small></article></section>
      <section className="card"><div className="card-head"><div><p className="section-kicker">Where to use</p><h2>你刚才问的功能，现在都在这里</h2></div><span className="live-badge">7 个明确入口</span></div><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(220px,1fr))", gap: 12 }}>{tabs.slice(1).map((item) => <button className="secondary-button" key={item.key} onClick={() => setTab(item.key)} style={{ textAlign: "left", minHeight: 86, whiteSpace: "normal" }}><b style={{ display: "block", marginBottom: 5 }}>{item.icon} {item.key}</b><span>{item.desc}</span><small style={{ display: "block", marginTop: 5 }}>打开 →</small></button>)}</div></section>
      <section className="card"><div className="card-head"><div><p className="section-kicker">Business value</p><h2>商户能看懂 AI 有没有产生价值</h2></div></div><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(180px,1fr))", gap: 12 }}><div><small>销售线索</small><h2>{data.summary.leads}</h2></div><div><small>预计商机</small><h2>{money(data.summary.pipelineCents)}</h2></div><div><small>已成交</small><h2>{money(data.summary.wonCents)}</h2></div><div><small>待处理人工工单</small><h2>{data.summary.openTickets}</h2></div><div><small>平均模型延迟</small><h2>{data.summary.avgLatencyMs} ms</h2></div></div></section>
    </>}
    {tab === "实时会话" && <CustomerServiceConsole canAdmin={canAdmin} onNotice={onNotice} view="conversations"/>}
    {tab === "FAQ" && <CustomerServiceConsole canAdmin={canAdmin} onNotice={onNotice} view="faq"/>}
    {data && tab === "数据报表" && <>
      <section className="metric-grid commercial-metrics"><article><span>近 30 天会话</span><strong>{data.summary.conversations}</strong><small>AI + 人工总接待</small></article><article><span>AI 自动化率</span><strong>{data.summary.automationRate}%</strong><small>减少人工重复回复</small></article><article><span>FAQ 命中</span><strong>{data.summary.faqHits}</strong><small>等于至少节省 {data.summary.modelCallsSaved} 次 LLM</small></article><article><span>人工转接</span><strong>{data.summary.handoff}</strong><small>{data.summary.handoffRate}% 转人工</small></article></section>
      <section className="card"><div className="card-head"><div><p className="section-kicker">14-day trend</p><h2>客服会话趋势</h2></div></div><div style={{ display: "flex", alignItems: "end", height: 220, gap: 8, padding: "20px 4px 0" }}>{data.daily.map((item) => <div key={item.day} style={{ flex: 1, minWidth: 16, display: "grid", alignItems: "end", height: "100%", gap: 5 }} title={`${item.day} · ${item.conversations} 会话 · AI解决 ${item.aiResolved} · 转人工 ${item.handoff}`}><div style={{ height: `${Math.max(item.conversations ? 8 : 2, item.conversations / maxDaily * 100)}%`, minHeight: 3, borderRadius: "8px 8px 3px 3px", background: "linear-gradient(180deg,#7253ea,#a78bfa)" }}/><small style={{ fontSize: 10, textAlign: "center" }}>{item.day.slice(5)}</small></div>)}</div></section>
      <section className="card"><div className="card-head"><div><p className="section-kicker">Visitor regions</p><h2>访客地区分布</h2></div></div><div style={{ display: "grid", gap: 8 }}>{data.countries.length ? data.countries.map((item) => <div key={item.country} style={{ display: "flex", justifyContent: "space-between", borderBottom: "1px solid #eef0f5", padding: "10px 0" }}><span>{item.country}</span><b>{item.count} 个会话</b></div>) : <p>暂无地区数据；接入 Cloudflare/CDN 后会自动读取国家/地区请求头。</p>}</div></section>
    </>}
    {data && tab === "Trace 日志" && <section className="card"><div className="card-head"><div><p className="section-kicker">AI diagnostics</p><h2>对话 Trace / 日志中心</h2><p>直接看 RAG、Embedding、Rerank 和大模型各阶段是否有有效数据。</p></div><span className="count-badge">{data.traces.length} traces</span></div><div style={{ display: "grid", gridTemplateColumns: "minmax(260px,.8fr) minmax(360px,1.2fr)", gap: 16 }}><div style={{ maxHeight: 600, overflow: "auto", display: "grid", gap: 8 }}>{data.traces.map((item) => <button key={item.id} className="secondary-button" onClick={() => setSelectedTrace(item.id)} style={{ textAlign: "left", whiteSpace: "normal", borderColor: selectedTrace === item.id ? "#7253ea" : undefined }}><b>{item.status} · {item.model}</b><small style={{ display: "block" }}>{item.question.slice(0, 100)}</small><small>{item.latencyMs} ms · {item.totalTokens} tokens · {time(item.createdAt)}</small></button>)}</div><div>{trace ? <><div style={{ display: "grid", gridTemplateColumns: "repeat(2,1fr)", gap: 8, marginBottom: 12 }}>{trace.stages.map((stage) => <article key={stage.name} style={{ border: "1px solid #e5e7eb", borderRadius: 12, padding: 12 }}><small>{stage.name}</small><b style={{ display: "block", margin: "4px 0" }}>{stage.status}</b><span>{stage.detail}</span></article>)}</div><h3>问题</h3><p>{trace.question}</p><h3>回答</h3><p style={{ whiteSpace: "pre-wrap" }}>{trace.answer || "—"}</p><h3>知识来源</h3><pre style={{ whiteSpace: "pre-wrap", maxHeight: 240, overflow: "auto" }}>{JSON.stringify(trace.sources, null, 2)}</pre></> : <p>暂无 Trace。</p>}</div></div></section>}
    {data && tab === "访客与跟进" && <section className="card"><div className="card-head"><div><p className="section-kicker">Visitor intelligence</p><h2>访客信息 + IP 地区 + 离线跟进</h2><p>IP 只显示脱敏值；地区优先读取 CDN 请求头。访客主动留邮箱后，离线时人工回复会自动邮件提醒。</p></div><span className="count-badge">{data.visitors.length} 位近期访客</span></div><div style={{ overflowX: "auto" }}><table style={{ width: "100%", borderCollapse: "collapse" }}><thead><tr><th>状态</th><th>最近问题</th><th>地区 / IP</th><th>来源</th><th>离线邮箱</th><th>最后在线</th></tr></thead><tbody>{data.visitors.map((item) => <tr key={item.id}><td><span className={online(item.lastVisitorSeenAt) ? "live-badge" : "count-badge"}>{online(item.lastVisitorSeenAt) ? "在线" : item.mode === "human" ? "人工" : "离线"}</span></td><td style={{ maxWidth: 300 }}>{item.lastQuestion || item.firstQuestion || "—"}</td><td>{[item.visitorCountry, item.visitorRegion, item.visitorCity].filter(Boolean).join(" / ") || "未知"}<small style={{ display: "block" }}>{item.visitorMaskedIp || "未取得 IP"}</small></td><td>{host(item.visitorReferer)}</td><td>{item.visitorEmail || "未留邮箱"}<small style={{ display: "block" }}>{item.offlineEmailSentAt ? `最近提醒 ${time(item.offlineEmailSentAt)}` : ""}</small></td><td>{time(item.lastVisitorSeenAt)}</td></tr>)}</tbody></table></div></section>}
    {tab === "网站 Widget" && <CommercialPanel canAdmin={canAdmin} members={members} onNotice={onNotice}/>}
  </div>;
}
