"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";

type TestRun = { passed: boolean; grounded: boolean; qualityScore: number; failureReason: string | null; createdAt: string };
type TestCase = { id: string; question: string; expectedAnswer: string; expectedDocument: string | null; shouldRefuse: boolean; latestRun: TestRun | null };
type QualityData = { threshold: number; summary: { cases: number; completed: number; passed: number; passRate: number | null }; cases: TestCase[] };

function tenantHeaders(init?: HeadersInit) { const headers = new Headers(init); const tenantId = localStorage.getItem("knowflow_tenant_id"); if (tenantId) headers.set("x-tenant-id", tenantId); return headers; }
async function call<T>(url: string, init?: RequestInit) { const response = await fetch(url, { ...init, headers: tenantHeaders(init?.headers) }); const data = await response.json() as T & { error?: string }; if (!response.ok) throw new Error(data.error || "请求失败"); return data; }

export default function QualitySuite({ canAdmin, knowledgeBaseId, knowledgeBaseName, onNotice }: { canAdmin: boolean; knowledgeBaseId: string; knowledgeBaseName: string; onNotice: (notice: { kind: "ok" | "error"; text: string }) => void }) {
  const [data, setData] = useState<QualityData | null>(null); const [busy, setBusy] = useState("");
  const [form, setForm] = useState({ question: "", expectedAnswer: "", expectedDocument: "", shouldRefuse: false });
  const load = useCallback(async () => setData(await call<QualityData>("/api/quality")), []);
  useEffect(() => { const timer = window.setTimeout(() => { void load().catch(() => undefined); }, 0); return () => window.clearTimeout(timer); }, [load]);
  async function create(event: FormEvent) { event.preventDefault(); setBusy("create"); try { await call("/api/quality", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "create", ...form }) }); setForm({ question: "", expectedAnswer: "", expectedDocument: "", shouldRefuse: false }); await load(); onNotice({ kind: "ok", text: "标准测试题已保存。" }); } catch (error) { onNotice({ kind: "error", text: error instanceof Error ? error.message : "保存失败" }); } finally { setBusy(""); } }
  async function run(id?: string) { setBusy(id || "all"); try { const result = await call<{ completed: number; passed: number }>("/api/quality", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: id ? "run" : "run_all", id, knowledgeBaseId }) }); await load(); onNotice({ kind: result.completed === result.passed ? "ok" : "error", text: `已在“${knowledgeBaseName}”运行 ${result.completed} 题，通过 ${result.passed} 题。` }); } catch (error) { onNotice({ kind: "error", text: error instanceof Error ? error.message : "运行失败" }); } finally { setBusy(""); } }
  async function remove(id: string) { if (!confirm("删除这道标准测试题及历史结果？")) return; await call(`/api/quality?id=${encodeURIComponent(id)}`, { method: "DELETE" }); await load(); }
  return <section className="card quality-suite"><div className="card-head"><div><p className="section-kicker">Regression evaluation</p><h2>标准测试题与上线门槛</h2><p>当前运行范围：<b>{knowledgeBaseName}</b>。每次修改知识库、切片或模型后运行；拒答题必须拒答，标准题必须命中指定答案和来源。</p></div><div className="quality-score"><b>{data?.summary.passRate == null ? "—" : `${data.summary.passRate}%`}</b><small>{data?.summary.passed || 0}/{data?.summary.completed || 0} 通过</small></div></div>
    <form className="quality-case-form" onSubmit={create}><textarea required value={form.question} onChange={(event) => setForm({ ...form, question: event.target.value })} placeholder="测试问题"/><input disabled={form.shouldRefuse} required={!form.shouldRefuse} value={form.expectedAnswer} onChange={(event) => setForm({ ...form, expectedAnswer: event.target.value })} placeholder={form.shouldRefuse ? "拒答题无需标准答案" : "标准答案关键内容（回答必须包含）"}/><input disabled={form.shouldRefuse} value={form.expectedDocument} onChange={(event) => setForm({ ...form, expectedDocument: event.target.value })} placeholder="指定来源文档（可选）"/><label><input type="checkbox" checked={form.shouldRefuse} onChange={(event) => setForm({ ...form, shouldRefuse: event.target.checked })}/> 资料不足时必须拒答</label><button className="secondary-button" disabled={!canAdmin || busy === "create"}>保存测试题</button><button className="primary-button" type="button" disabled={!data?.cases.length || Boolean(busy) || !knowledgeBaseId} onClick={() => void run()}>运行全部</button></form>
    <div className="quality-case-list">{!data?.cases.length ? <div className="source-empty">至少建立 10 道业务标准题和 3 道拒答题，才能把回答质量变成可验收指标。</div> : data.cases.map((item) => <article key={item.id}><span className={item.latestRun ? (item.latestRun.passed ? "case-pass" : "case-fail") : "case-pending"}>{item.latestRun ? (item.latestRun.passed ? "通过" : "失败") : "未运行"}</span><div><b>{item.question}</b><small>{item.shouldRefuse ? "预期：拒答" : `预期：${item.expectedAnswer}`}{item.expectedDocument ? ` · 来源 ${item.expectedDocument}` : ""}</small>{item.latestRun && <p>可靠度 {item.latestRun.qualityScore.toFixed(3)} · {item.latestRun.grounded ? "有依据回答" : "安全拒答"}{item.latestRun.failureReason ? ` · ${item.latestRun.failureReason}` : ""}</p>}</div><button onClick={() => void run(item.id)} disabled={Boolean(busy)}>运行</button>{canAdmin && <button className="ghost-danger" onClick={() => void remove(item.id)}>删除</button>}</article>)}</div>
  </section>;
}
